name: listick
description: "A new Flutter project."
publish_to: "none"
version: 0.1.2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.2.0
  image_picker: ^1.0.7
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
