// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBXXlKnZxWxTagbGpAqLyRDu53id8L6fI',
    appId: '1:351822399351:web:240c4f27ecdb87b7400372',
    messagingSenderId: '351822399351',
    projectId: 'listick-app-2024',
    authDomain: 'listick-app-2024.firebaseapp.com',
    storageBucket: 'listick-app-2024.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUFVThM6EUxXG9BtEJVsYHVLwOPBWiXsI',
    appId: '1:351822399351:android:88f170f75a10487c400372',
    messagingSenderId: '351822399351',
    projectId: 'listick-app-2024',
    storageBucket: 'listick-app-2024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCydjRyNHyqElHWJ8yb3JPX4B3frD9GN2E',
    appId: '1:351822399351:ios:493ea2d12a90bf19400372',
    messagingSenderId: '351822399351',
    projectId: 'listick-app-2024',
    storageBucket: 'listick-app-2024.firebasestorage.app',
    iosClientId:
        '351822399351-pqgm4ati3juf413nhq6uavp2f06r4f1h.apps.googleusercontent.com',
    iosBundleId: 'com.dodapps.listick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCydjRyNHyqElHWJ8yb3JPX4B3frD9GN2E',
    appId: '1:351822399351:ios:493ea2d12a90bf19400372',
    messagingSenderId: '351822399351',
    projectId: 'listick-app-2024',
    storageBucket: 'listick-app-2024.firebasestorage.app',
    iosClientId:
        '351822399351-pqgm4ati3juf413nhq6uavp2f06r4f1h.apps.googleusercontent.com',
    iosBundleId: 'com.dodapps.listick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBXXlKnZxWxTagbGpAqLyRDu53id8L6fI',
    appId: '1:351822399351:web:71dbec39615cce4e400372',
    messagingSenderId: '351822399351',
    projectId: 'listick-app-2024',
    authDomain: 'listick-app-2024.firebaseapp.com',
    storageBucket: 'listick-app-2024.firebasestorage.app',
  );
}
